version: "3.9"

services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    networks:
      - proxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      CONFIGS: 1
      TASKS: 1
      NODES: 1
      INFO: 1
      LOG_LEVEL: notice
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints: [node.role == manager]

  caddy:
    image: gabemocan/swarm:caddy-2.6.2
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      CADDY_INGRESS_NETWORKS: caddy
      DOCKER_HOST: tcp://docker-proxy:2375
    volumes:
      - caddy_data:/data
    networks:
      - caddy
      - proxy-network
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:2019/metrics || exit 1
      interval: 30s
      timeout: 5s
      start_period: 1m
    deploy:
      placement:
        constraints: [node.role == manager]
      update_config:
        failure_action: rollback
      labels:
        # Set ACME definitions
        caddy_0.email: ${EMAIL?Variable not set}  # Set valid e-mail for SSL cert auto-generation
        # Uncomment the line below to enable Cloudflare's DNS-01 TLS challenge, which does not need any open ports
        # caddy_0.acme_dns: "cloudflare ${CF_API_TOKEN?Variable not set}"

volumes:
  caddy_data:

networks:
  proxy-network:
  # This external network will be used to expose services later on
  caddy:
    external: true
