version: "3.9"

######################################################## BASE TEMPLATES ########################################################

x-client_data: &client_data
  SCOPE: ${SCOPE?Variable not set}
  TZ: ${TZ?Variable not set}

############################################################ SERVICES ############################################################

services:
  mariadb:
    image: bitnami/mariadb:10.6
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - database-network
    environment:
      <<: *client_data
      MARIADB_USER: ${DB_USERNAME?Variable not set}
      MARIADB_DATABASE: ${DB_DATABASE?Variable not set}
      MARIADB_PASSWORD: ${DB_PASSWORD?Variable not set}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD?Variable not set}

  wordpress:
    image: bitnami/wordpress:6
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - database-network
      - caddy
    environment:
      <<: *client_data
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: ${DB_USERNAME?Variable not set}
      WORDPRESS_DATABASE_NAME: ${DB_DATABASE?Variable not set}
      WORDPRESS_DATABASE_PASSWORD: ${DB_PASSWORD?Variable not set}
    deploy:
      labels:
        # This will enable site access through HTTPS. e.g: https://home.example.com
        caddy: home.${DOMAIN?Variable not set}
        caddy.reverse_proxy: "{{upstreams 8080}}"

########################################################### CRON-JOBS ##########################################################
  # This service will produce daily backups at 00:00 local time
  backup-wordpress:
    image: gabemocan/swarm:rclone-1.61.1
    cap_add:
      - SYS_NICE
    environment:
      <<: *client_data
      RCLONE_LOG_LEVEL: ERROR
      RCLONE_CONFIG_S3_TYPE: s3
      RCLONE_CONFIG_S3_NO_CHECK_BUCKET: "true"
      RCLONE_CONFIG_S3_BUCKET: ${S3_BUCKET?Variable not set}
      RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY?Variable not set}
      RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${S3_SECRET_KEY?Variable not set}
      RCLONE_CONFIG_S3_ENDPOINT: ${S3_ENDPOINT?Variable not set}
    volumes:
      - mariadb_data:/backup/mariadb
      - wordpress_data:/backup/wordpress
    deploy:
      replicas: 0
      placement:
        constraints: [node.role == manager]
      labels:
        # These labels configure cronjob schedule
        swarm.cronjob.enable: "true"
        swarm.cronjob.schedule: "00 00 * * *"
        swarm.cronjob.skip-running: "true"
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 1h
    command: ["volume_backup.sh"]

volumes:
  mariadb_data:
  wordpress_data:

networks:
  database-network:
  caddy:
    external: true
